### ISSUE TITLE
allthetweaks need kubejs 1

### ISSUE THREAD

**Issue by Ase2002** [AllTheMods/all-the-mods-6-expert#11]
allthetweaks need kubejs 1 is an error i get when trying to start mincraft even though i have the latest kubejs and the latest allthetweaks
can anyone help?

**Comment by Pdiddy973** [comment]
This is not the right place to report this issue...but likely a fresh install will fix your issue. And we don't recommend updating mods in the pack.

**Comment by Ase2002** [comment]
> This is not the right place to report this issue...but likely a fresh install will fix your issue. And we don't recommend updating mods in the pack.

thank you

**Comment by thevortex** [comment]
this issue is resolved with an update to tweaks, it was related to a change in forge and has been fixed here https://www.curseforge.com/minecraft/mc-mods/all-the-tweaks/files/3291361

**Comment by Ase2002** [comment]
> this issue is resolved with an update to tweaks, it was related to a change in forge and has been fixed here https://www.curseforge.com/minecraft/mc-mods/all-the-tweaks/files/3291361

Thank you i will download and try thanks
